name: Build and deploy Grading and Commons JAR apps to Azure Web Apps

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'


      - name: Install Parent POM
        run: mvn -N clean install


      - name: Build and install Commons module
        run: mvn -pl commons clean install

      # Step 3: Build Grading module
      - name: Build Grading module
        run: mvn -pl grading clean install

      # Upload Grading artifact
      - name: Upload Grading artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: grading-app
          path: 'grading/target/grading-0.0.1-SNAPSHOT.jar'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      # Deploy Grading module
      - name: Download Grading artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: grading-app

      - name: Deploy Grading JAR to Azure Web App
        id: deploy-grading
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'INNO-testvision-grading'
          slot-name: 'Production'
          package: 'grading-0.0.1-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3AC5B4C41514457FBE064F33BD70B76C  }}