name: Build and deploy Exam JAR app to Azure Web App

on:
  push:
    branches:
      - master_dev
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Install Parent POM
        run: mvn -N clean install

      - name: Build and install Commons module
        run: mvn -pl commons clean install


      - name: Build Exam module
        run: mvn -pl exam clean install

      - name: Upload Exam artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: exam-app
          path: 'exam/target/exam-0.0.1-SNAPSHOT.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'exam_Production'


    steps:
      - name: Download Exam artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: exam-app

      - name: Deploy Exam JAR to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'exam'
          slot-name: 'Production'
          package: 'exam-0.0.1-SNAPSHOT.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A4DC66B24BB45DF910292F932D2C9D4 }}